version: "3"
services:
  mysql1:
    image: "bitnami/mysql:5.7"

    ports:
      - "3310:3306"
    container_name: mysql11
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
  mysql2:
    image: "bitnami/mysql:5.7"
    ports:
      - "3311:3306"
    container_name: mysql22
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
    depends_on:
      - mysql1
    links:
      - mysql1
      - mysql1:mysql33